sudo: required
language: generic

services:
  - docker

before-install:
  - docker build -t kanhajeevan/react-docker -f Dockerfile.dev .

script:
  - docker run -e CI=true kanhajeevan/react-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "learn-docker-react"
  env: "LearnDockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-153948048593"
  bucket_path": "learn-docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
