sudo: required
language: generic
services:
  - docker
before-install:
  - docker build -t kanhajeevan/react-docker -f Dockerfile.dev .
script:
  - docker run -e CI=true kanhajeevan/react-docker npm run test -- --coverage
